task :default => :test_unit
files_to_watch = "lib/toredis.rb test/toredis_spec.rb test/test_toredis.rb " +
                 "test/fakecsvs.rb test/mock_redis.rb test/test_simu_data.rb " +
                 "lib/simu_data.rb"
includes = "-I./test -I./lib"

tunit_cmd = "ruby #{includes} test/test_toredis.rb"
desc "test"
task :test_unit do
  sh tunit_cmd
end

desc "rspec"
task :rspec do
  rspec_cmd = "rspec #{includes} -c -fn test/toredis_spec.rb"
  sh rspec_cmd
end

desc "Run watchr"
task :watch do
  #cmd = "ruby ./test/watcher.rb '#{rspec_cmd}' #{files_to_watch}"
  cmd = "ruby ./test/watcher.rb '#{tunit_cmd}' #{files_to_watch}"
  sh cmd
end
